name: PPR UI CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "ppr-ui/**"

jobs:
  ppr-ui-ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./ppr-ui

    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          make setup
        env:
          CI: true
      - name: Run Lint
        run: |
          make lint
        env:
          CI: true
      - name: Run Unit Tests
        run: |
          make test
        env:
          CI: true
          PPR_API_KEY: ${{ secrets.PPR_API_KEY }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-ppr-ui
          fail_ci_if_error: true
      - name: build to check strictness
        run: |
          make build-nc
        env:
          CI: true
